# Generated by Django 2.0.5 on 2018-06-06 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180602_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5d26f019-b32e-4651-a1f7-b85a551632dd')),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_posts', to='blog.Tag'),
        ),
    ]
