# Generated by Django 2.0.5 on 2018-06-13 22:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180611_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
