# Generated by Django 2.1.3 on 2018-11-27 19:56

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181127_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
