# Generated by Django 2.1.3 on 2018-11-27 20:12

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_search'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogpost',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='blog_blogpo_search_9066bf_gin'),
        ),
    ]
